import LocalizedStrings from "react-localization";

const localized = new LocalizedStrings({
  en: {
    successfully: "Successfully",
    unsuccessful: "Unsuccessful",
    authorization: "Authorization",
    errorName: "Enter a name of at least 3 characters",
    nickname: "Your username",
    errorPassword: "Enter a password of 5 characters or more",
    password: "Password",
    language: "Language",
    register: "Register",
    enter: "Login",
    mobileErrorTitle: "Application unavailable",
    mobileErrorText:
      "The mobile version of the application is under development. Please open the application on a larger screen",
    whichLogsShow: "Which logs to show:",
    allLogs: "All logs",
    onlineStore: "Online store",
    administrativePanel: "Administrative panel",
    createTestLog: "Create a test log",
    goOut: "Exit",
    project: "Project",
    nameError: "Error name",
    details: "Details",
    callStack: "Call Stack",
    date: "Date",
    system: "System",
    browser: "Browser",
    user: "User",
  },
  ru: {
    successfully: "Успешно",
    unsuccessful: "Неуспешно",
    authorization: "Авторизация",
    errorName: "Введите имя от 3 символов",
    nickname: "Ваш логин",
    errorPassword: "Введите пароль от 5 символов",
    password: "Пароль",
    language: "Язык",
    register: "Зарегистрироваться",
    enter: "Войти",
    mobileErrorTitle: "Приложение недоступно",
    mobileErrorText:
      "Мобильная версия приложения находится в разработке. Пожалуйста, откройте приложение на большом экране",
    whichLogsShow: "Какие логи показывать:",
    allLogs: "Все логи",
    onlineStore: "Онлайн магазин",
    administrativePanel: "Административная панель",
    createTestLog: "Создать тестовый лог",
    goOut: "Выйти",
    project: "Проект",
    nameError: "Имя ошибки",
    details: "Детали",
    callStack: "Стек вызова",
    date: "Дата",
    system: "Система",
    browser: "Браузер",
    user: "Пользователь",
  },
});

export default localized;
